import { ServiceCode } from "../constants/servicecodes";

export const SERVICE_CODE_LABELS: Record<ServiceCode, string> = {
  OPD_CONSULTATION: "OPD Consultation",
  IPD_HOSPITALIZATION: "IPD Hospitalization",
  EMERGENCY_CARE: "Emergency Care",
  DIAGNOSTIC_LAB: "Diagnostic Lab",
  IMAGING_XRAY: "X-Ray Imaging",
  IMAGING_MRI: "MRI Imaging",
  IMAGING_CT: "CT Scan Imaging",
  PHARMACY_OUTPATIENT: "Outpatient Pharmacy",
  PHARMACY_INPATIENT: "Inpatient Pharmacy",
  SURGERY_GENERAL: "General Surgery",
  SURGERY_SPECIALIZED: "Specialized Surgery",
  MATERNITY_NORMAL: "Maternity (Normal)",
  MATERNITY_C_SECTION: "Maternity (C-Section)",
  PEDIATRIC_CARE: "Pediatric Care",
  MENTAL_HEALTH: "Mental Health",
  PHYSIOTHERAPY: "Physiotherapy",
  DENTAL_BASIC: "Basic Dental",
  DENTAL_SURGICAL: "Dental Surgery",
  VISION_CHECK: "Vision Check",
  OPTICAL_LENSES: "Optical Lenses",
  ICU_CARE: "ICU Care",
  DAY_CARE_PROCEDURE: "Day Care Procedure",
  HOME_HEALTHCARE: "Home Healthcare",
  PREVENTIVE_HEALTH_CHECK: "Preventive Health Check",
  VACCINATION: "Vaccination",
  ORGAN_TRANSPLANT: "Organ Transplant",
  ONCOLOGY_CHEMO: "Oncology – Chemotherapy",
  ONCOLOGY_RADIATION: "Oncology – Radiation",
  RENAL_DIALYSIS: "Renal Dialysis",
  AMBULANCE_SERVICE: "Ambulance Service"
};
